# Generated by Django 4.1.13 on 2024-03-25 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField()),
                ('skills_score', models.FloatField()),
                ('edu_score', models.FloatField()),
                ('exp_score', models.FloatField()),
                ('summarize', models.TextField()),
                ('uploaded_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='myapp.uploadeddocument')),
            ],
        ),
    ]
