# Generated by Django 4.1.13 on 2024-03-25 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0002_analysisresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='grammarcheck',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='suggestions',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='upgraded_pdf',
            field=models.FileField(default='', upload_to='upgraded_pdfs/'),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='edu_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='exp_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='overall_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='skills_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='summarize',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='UpdatedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('document', models.FileField(upload_to='upgraded_pdfs/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
