# Generated by Django 4.1.13 on 2024-04-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_analysisresult_grammarcheck_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='missingskills',
            field=models.TextField(default='[]'),
        ),
        migrations.DeleteModel(
            name='UpdatedDocument',
        ),
    ]
