# Generated by Django 4.1.13 on 2024-04-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_analysisresult_missingskills_delete_updateddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='googleimage',
            field=models.TextField(default=''),
        ),
    ]
